### ISSUE TITLE
Add link to F-Droid store?

### ISSUE THREAD

**Issue by njam** [criticalmaps/criticalmaps-web#32]
How about linking to the F-Droid store from the homepeage (besides Google Play store)?

Link: https://f-droid.org/packages/de.stephanlindauer.criticalmaps/
(See https://github.com/criticalmaps/criticalmaps-android/issues/222)

**Comment by stephanlindauer** [comment]
good point. however i wouldn't want to make it too prominnent because people might get confused (not knowing what fdroid is) and the other blocker for me is that it's been a bit of a struggle releasing new versions to f-droid lately (with the latest version still missing from their store).
i would suggest postponing until releases are back to normal with f-droid.

**Comment by stephanlindauer** [comment]
fdroid seems back to normal. 
@zutrinken can you come up with a nice way to also display the frdoid icon here:
![image](https://user-images.githubusercontent.com/1323145/62284776-9dd8e280-b454-11e9-95d9-7a9cf1c9128f.png)
link should go to https://f-droid.org/en/packages/de.stephanlindauer.criticalmaps/
